services:

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.data/pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=itarget
      - POSTGRES_DB=employees_management_system
      - POSTGRES_PASSWORD=1234
    networks:
      - app_network

  app:
    build: .
    ports:
      - 8501:8501
    volumes:
      - ./:/app
    networks:
      - app_network

networks:

  app_network:
    driver: bridge