services:

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.data/pgsql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - app_network

  app:
    build: .
    ports:
      - 8501:8501
    volumes:
      - ./:/app
    env_file:
      - ./.env
    networks:
      - app_network

networks:

  app_network:
    driver: bridge